### ISSUE TITLE
nicknames panel doesn't work on ServerConfig

### ISSUE THREAD

**Issue by vilchu** [Ekibunnel/BetterDiscordAddons#2]
![image](https://user-images.githubusercontent.com/55512609/203833041-3b22ccae-9317-48cd-97f6-757a357419dd.png)
![image](https://user-images.githubusercontent.com/55512609/203833081-dba82b1c-0531-4327-af7b-e0bcfa2be54c.png)

**Comment by Ekibunnel** [comment]
Not an issue with the plugin itself, you need to use the lastest version of `ZeresPluginLibrary` https://github.com/rauenzi/BDPluginLibrary/commit/94d202bc8044b5bbf86ee0635395d36c0abbf040
Currently you need to build it yourself since the downloadable version on betterdiscord.app is out of date.

**Comment by Ekibunnel** [comment]
Please use this version [Plugins/ServerConfig/0PluginLibrary.plugin.js](https://github.com/Ekibunnel/BetterDiscordAddons/blob/main/Plugins/ServerConfig/0PluginLibrary.plugin.js) of `ZeresPluginLibrary` for the time being.

I will delete this when the up to date version hit betterdiscord.app

**Comment by vilchu** [comment]
Okay, thank you so much and sorry for late reply!

**Comment by Ekibunnel** [comment]
The [ZeresPluginLibrary on betterdiscord.app](https://betterdiscord.app/plugin/ZeresPluginLibrary) is up to date now ( `2.0.10` )

Please use that.
